kind: pipeline
name: default

steps:
- name: install
  image: johnpapa/angular-cli
  commands:
    - npm install

- name: test
  image: trion/ng-cli-karma:6.2.1
  commands:
    - cd frontend-movie
    - ng test --progress false --watch false

- name: build
  image: johnpapa/angular-cli
  commands:
    - cd frontend-movie
    - ng build --prod --base-href "https://peeramethaw.github.io/Movie/"

